# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g newman
    newman run VDPromo/ValidPromotions.postman_collection.json -e VDPromo/ValidPromotions.postman_environment.json
  displayName: 'Run cenários de teste API Valid Promotions'