# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Tests
    jobs:
      - job: Newman
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '16.x'
            displayName: 'Install Node.js'

          - script: |
              npm install -g newman
              newman run ValidPromotions.postman_collection.json -e ValidPromotions.postman_environment.json
            displayName: 'Run Cenários de Testes Valid Promotion' 